name: winplan
description: winplan app.
publish_to: 'none'

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  awesome_dialog: ^3.0.2
  cupertino_icons: ^1.0.5
  cloud_firestore: ^4.4.3
  accordion: ^2.5.1
  animated_toggle_switch: ^0.6.1
  auto_size_text: ^3.0.0
  background_locator_2: ^2.0.6-dev.2
  badges: ^3.0.2
  bloc: ^8.1.1
  card_swiper: ^2.0.4
  country_flags: ^1.1.0
  date_picker_timeline: ^1.2.3
  dropdown_button2: ^1.9.4
  easy_localization: ^3.0.1
  easy_refresh: ^3.3.1

  firebase_messaging: ^14.2.6
  firebase_analytics: ^10.1.5
  flutter_local_notifications: ^13.0.0
  firebase_core: ^2.7.1
  flip_card: ^0.7.0
  flutter_bloc: ^8.1.2
  flutter_easyloading: ^3.0.5
  flutter_localizations:
    sdk: flutter
  flutter_map: ^3.1.0
  flutter_map_marker_cluster: ^1.0.2
  flutter_sms: ^2.3.3
  flutter_svg: ^2.0.2
  fluttertoast: ^8.2.1
  flutter_vector_icons: ^2.0.0
  
  formz: ^0.4.1
  just_the_tooltip: ^0.0.12
  liquid_progress_indicator: ^0.4.0
  logger: ^1.2.2
  google_fonts: ^4.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  loading_animation_widget: ^1.2.0+4
  ngi_api:
    path: packages/ngi_api
  ngi_repository:
    path: packages/ngi_repository
  os_detect: ^2.0.1
  permission_handler: ^10.2.0
  pin_code_fields: ^7.4.0
  quickalert: ^1.0.1
  signature: ^5.3.2
  sliding_up_panel2: ^3.2.2
  text_scroll: ^0.1.2
  timeago: ^3.3.0
  timeago_flutter: ^1.2.0
  tuple: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.1
  path_provider: ^2.0.13
  location_permissions: ^4.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  assets:
    - assets/translations/
    - assets/images/flags/
    - assets/images/flag/
    - assets/images/slider/
    - assets/images/alerts/
    - assets/images/fleet/building/
    - assets/images/fleet/bus/
    - assets/images/fleet/commercial_vehicle/
    - assets/images/fleet/concrete_mixer/
    - assets/images/fleet/container/
    - assets/images/fleet/container_truck/
    - assets/images/fleet/dump_truck/
    - assets/images/fleet/fuel_tank_truck/
    - assets/images/fleet/camion_gms_frais/
    - assets/images/fleet/camion_gms_sec/
    - assets/images/fleet/camion_clv_frais/
    - assets/images/fleet/camion_clv_sec/
    - assets/images/fleet/guide/
    - assets/images/fleet/home/
    - assets/images/fleet/light_truck/
    - assets/images/fleet/long_truck/
    - assets/images/fleet/pickup_truck/
    - assets/images/fleet/small_truck/
    - assets/images/fleet/motorcycle/
    - assets/images/fleet/person/
    - assets/images/fleet/personal_vehicle/
    - assets/images/fleet/pilgrim/
    - assets/images/fleet/refrigerated_truck/
    - assets/images/fleet/refrigerator/
    - assets/images/fleet/shelter/
    - assets/images/fleet/ship/
    - assets/images/fleet/shop/
    - assets/images/fleet/speedboat/
    - assets/images/fleet/store/
    - assets/images/fleet/tank/
    - assets/images/fleet/tank_truck/
    - assets/images/fleet/tank_truck_new/
    - assets/images/fleet/trailer_truck/
    - assets/images/fleet/train/
    - assets/images/fleet/truck/
    - assets/images/fleet/utility_truck/
    - assets/images/fleet/warehouse/
    - assets/images/brands/
    - assets/images/containerimg/
    - assets/images/user/
    - assets/images/login/
    - assets/images/sidebar/
    - assets/images/cars/
    - assets/images/sensors/
    - assets/images/history/
    - assets/images/actions/
    - assets/images/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
