name: ngi_repository
description: A repository that handles asset related requests.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  hive  : ^2.2.3
  http: ^0.13.5
  json_annotation: ^4.8.0
  meta: ^1.8.0
  ngi_api:
    path: ../ngi_api
  socket_io_client: ^1.0.2
  tuple: ^2.0.1

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  test: ^1.23.1
  very_good_analysis: ^4.0.0+1
