name: ngi_api
description: The interface and models for an API providing access to assets.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  equatable: ^2.0.5
  hive  : ^2.2.3
  http: ^0.13.5
  json_annotation: ^4.8.0
  latlong2: ^0.8.1
  logger: ^1.2.2
  meta: ^1.8.0
  tuple: ^2.0.1

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  test: ^1.23.1
  very_good_analysis: ^4.0.0+1
